### ISSUE TITLE
JDK11出现包错误：NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by niefy** [chillzhuang/blade-tool#1]
## 环境 
JDK11 
## 问题描述
org.springblade.core.secure.utils.SecureUtil中使用的Base64处理工具包javax.xml.bind.DatatypeConverter无法使用，报如下错误：
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.springblade.core.secure.utils.SecureUtil.<clinit>(SecureUtil.java:51)
## 说明
使用JDK8重新编译运行正常

**Comment by chillzhuang** [comment]
收到，稍后处理

**Comment by chillzhuang** [comment]
已修复 改为 java.util.Base64
