### ISSUE TITLE
关于jwt token 的签名key在代码中暴露且无法注入修改的问题

### ISSUE THREAD

**Issue by wxlzmt** [chillzhuang/blade-tool#4]
在代码文件
```
/blade-core-launch/src/main/java/org/springblade/core/launch/constant/TokenConstant.java
``` 
内，有定义变量
```java
String SIGN_KEY = "Blade";
```

该变量的值在 
```
/blade-core-secure/src/main/java/org/springblade/core/secure/utils/SecureUtil.java
```
中作为 jwt token的加解密的签名key进行使用。

从而导致引用本项目作为类库使用时，token生成时用的签名key必须是"Blade"，由blade-core-secure拦截鉴权时，自动根据签名key值"Blade"进行token解密。

本项目遵从 LGPL 协议，从而引用本项目作为类库使用时，不能修改（源码）签名key，以至于人人都可以对jwt token进行解密了。。。

这个问题如何解决？使用时通过获取作者授权然后修改源码？或者是参与付费进行二次开发？

**Comment by chillzhuang** [comment]
下版本会增加可配置项，目前可以参考springboot版本，覆盖secureUtil达到修改的目的。
https://gitee.com/smallc/SpringBlade/blob/2.0-boot/src/main/java/org/springblade/core/secure/utils/SecureUtil.java
